#!/bin/bash

branch=$(git branch --show-current)

# Check if branch exist in remote
if ! git ls-remote --exit-code --heads origin "$branch"; then
    # Create branch if does not exist
    echo "Branch does not exist on remote. Creating..."
    git push --set-upstream origin "$branch"
fi

echo "Pulling..."
git pull

git add -A
git status
echo "Do you want to continue? (Y/N)"
read proceed
if [[ $proceed == "Y" || $proceed == "y" || $proceed == "s" || $proceed == "" ]]; then
    git commit -m "$1"
    echo "Pushing..."
    git push
else
    echo "Operation cancelled."
fi

