#!/bin/bash

branchName="$1"
stashName="stash_for_$branchName"

if [ -n "$branchName" ]
then
    git stash save "$stashName"

    if ! git ls-remote --heads origin "$branchName" | grep -q "$branchName"
    then
        if ! git branch -l | grep -q -w "^ *$branchName\$"
        then
            git switch -c "$branchName"
        else
            git switch "$branchName"
        fi
    else
        git fetch origin "$branchName"
        git switch "$branchName"
    fi

    # Gets the specific stash ID
    stashID=$(git stash list | grep "$stashName" | awk '{print $1}' | sed 's/://')

    # If it exists, apply
    if [ ! -z "$stashID" ]
    then
        git stash pop "$stashID"
    fi
else
    echo "Branch name is not specified"
fi


