git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: 'a'
    context: 'files'
    command: "git {{if .SelectedFile.HasUnstagedChanges}} add {{else}} reset {{end}} {{.SelectedFile.Name | quote}}"
    description: 'Toggle file staged'
  - key: 's'
    context: 'localBranches'
    command: "git s {{.SelectedLocalBranch.Name}}"
    description: 'Switch or Create branch stashing changes'
    loadingText: 'Switching branch'
  - key: 'p'
    context: 'localBranches'
    command: "git fetch origin {{.SelectedLocalBranch.Name}}:{{.SelectedLocalBranch.Name}} --update-head-ok"
    description: 'Pull selected branch'
    loadingText: 'Pulling branch'
  - key: '<c-p>'
    context: 'global'
    prompts:
      - type: 'input'
        title: 'What is the commit text?'
        key: 'CommitText'
        initialValue: ''
    command: 'git p "{{.Form.CommitText}}"'
    description: 'Add, Commit & Push all changes'
    loadingText: 'Pushing changes'
  - key: 'n'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'a feature branch'
            value: 'feature'
          - name: 'bugfix'
            description: 'a bugfix branch'
            value: 'bugfix'
          - name: 'hotfix'
            description: 'a hotfix branch'
            value: 'hotfix'
          - name: 'release'
            description: 'a release branch'
            value: 'release'
      - type: 'input'
        title: 'What is the new branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git s {{.Form.BranchType}}/{{.Form.BranchName}}"
    description: 'Create new branch stashing changes'
    loadingText: 'Creating branch'
keybinding:
  universal:
    prevBlock-alt: 'K' # scroll left within list view
    nextBlock-alt: 'J' # scroll right within list view
    scrollUpMain-alt1: '<c-k>' # main panel scroll up
    scrollDownMain-alt1: '<c-j>'
